# Generated by Django 5.0 on 2024-01-06 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.CharField(max_length=50)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=8)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.order')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('category', models.CharField(max_length=50)),
                ('available_quantity', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_time', models.DateTimeField(auto_now_add=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
            ],
        ),
        migrations.DeleteModel(
            name='APIFuncionario',
        ),
        migrations.RemoveField(
            model_name='apiorderedproduct',
            name='order',
        ),
        migrations.RemoveField(
            model_name='apivenda',
            name='order',
        ),
        migrations.RemoveField(
            model_name='apiorderedproduct',
            name='product',
        ),
        migrations.RemoveField(
            model_name='apiproduct',
            name='category',
        ),
        migrations.RemoveField(
            model_name='apivenda',
            name='metodo_pagamento',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.product'),
        ),
        migrations.DeleteModel(
            name='APIOrder',
        ),
        migrations.DeleteModel(
            name='APIOrderedProduct',
        ),
        migrations.DeleteModel(
            name='APIProduct',
        ),
        migrations.DeleteModel(
            name='APIVenda',
        ),
    ]
