# Generated by Django 5.0 on 2024-01-06 10:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_order_orderitem_product_sale_delete_apifuncionario_and_more'),
        ('vendas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
            ],
        ),
        migrations.RemoveField(
            model_name='venda',
            name='metodo_pagamento',
        ),
        migrations.RemoveField(
            model_name='venda',
            name='order',
        ),
        migrations.DeleteModel(
            name='MetodoPagamento',
        ),
        migrations.DeleteModel(
            name='Venda',
        ),
    ]
