# Generated by Django 5.0 on 2024-01-09 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0003_order_finished'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='table',
            field=models.IntegerField(),
        ),
    ]
